<?xml version="1.0" encoding="utf-8"?>
<SchemePartition SchemeVersion="4.0.0.2" ID="bc3e1376-a8e1-4256-bf84-1bfc7a49c95f" Name="Acl">
	<Dependencies>
		<SchemePartition ID="29f90c69-c1ef-4cbf-b9d5-7fc91cd68c67" Name="Default" />
	</Dependencies>
	<SchemeTable ID="b7538557-04c6-43d4-9d7a-4412dc1ed103" Name="Acl" IsExternal="true" />
	<SchemeTable ID="5cca17a2-50e3-4b20-98c2-2f6ed9ce31fa" Name="AclGenerationInfo" IsExternal="true" />
	<SchemeTable ID="c2c3b955-ca13-4e63-83aa-cb033ebdce57" Name="AclGenerationRuleExtensions" IsExternal="true" />
	<SchemeTable ID="5518f35a-ea30-4968-983d-aec524aeb710" Name="AclGenerationRules" IsExternal="true" />
	<SchemeTable ID="b55966a9-f474-47c9-b025-8e3408208646" Name="AclGenerationRuleTriggerModes" IsExternal="true" />
	<SchemeTable ID="24e6a4b4-7e51-4429-8bb7-648a840e026b" Name="AclGenerationRuleTriggers" IsExternal="true" />
	<SchemeTable ID="59827979-5949-4bb2-896d-dc8b5a238a32" Name="AclGenerationRuleTriggerTypes" IsExternal="true" />
	<SchemeTable ID="930de8d2-2496-4523-9ea2-800d229fd808" Name="AclGenerationRuleTypes" IsExternal="true" />
	<SchemeTable ID="6d2ec0d3-4980-45f3-aa64-ab79eb9f4da1" Name="ConditionsVirtual" IsExternal="true" />
	<SchemeTable ID="6963c76f-5e8d-49b5-80a3-f2ec342de0bf" Name="ConditionUsePlaces" IsExternal="true" />
	<SchemeTable ID="06245b07-be2a-40de-aec8-bfd367860930" Name="FieldChangedCondition" IsExternal="true" />
	<SchemeTable ID="312b1519-8079-44d7-a5b4-496db41da98c" Name="NestedRoles" IsExternal="true" />
	<SchemeTable ID="dd329f32-adf0-4336-bd9e-fa084c0fe494" Name="RoleDeputiesNestedManagement" IsExternal="true" />
	<SchemeTable ID="0958f50b-8fd2-4e65-9531-fd540f3150ab" Name="RoleDeputiesNestedManagementTypes" IsExternal="true" />
	<SchemeTable ID="a8c71408-d1a3-4dbc-abcb-287dd7b7c648" Name="RoleDeputiesNestedManagementTypesVirtual" IsExternal="true" />
	<SchemeTable ID="c9bf7542-de37-4fad-9cda-6b1a5a4964b7" Name="RoleDeputiesNestedManagementUsers" IsExternal="true" />
	<SchemeTable ID="6d0cfd99-aa36-4992-9231-eea478138fe6" Name="RoleDeputiesNestedManagementUsersVirtual" IsExternal="true" />
	<SchemeTable ID="3937aa4f-0658-4e8b-a25a-911802f1fa82" Name="RoleDeputiesNestedManagementVirtual" IsExternal="true" />
	<SchemeTable ID="3b9d9643-ed47-4301-94b2-8eedcabc23bc" Name="SectionChangedCondition" IsExternal="true" />
	<SchemeTable ID="c44db46a-349f-45ec-b0ab-ec212c09b276" Name="SmartRoleGeneratorInfo" IsExternal="true" />
	<SchemeTable ID="5f3a0dbc-2fc4-4269-8a5d-eb95f39970ba" Name="SmartRoleGenerators" IsExternal="true" />
	<SchemeTable ID="73cbcd25-8709-4c3d-9091-3db6ccba5055" Name="SmartRoleMembers" IsExternal="true" />
	<SchemeTable ID="844013f9-7faa-422a-b583-2b04ae46f0be" Name="SmartRoles" IsExternal="true" />
	<SchemeTable ID="059e1354-8b89-4e86-8fa1-29395e952926" Name="TaskConditionCompletionOptions" IsExternal="true" />
	<SchemeTable ID="b59a92cb-8414-4a3d-91f9-9d41de829d3f" Name="TaskConditionFunctionRoles" IsExternal="true" />
	<SchemeTable ID="48dcb84f-1518-4de4-8995-86c4e75a1d03" Name="TaskConditionSettings" IsExternal="true" />
	<SchemeTable ID="a3777728-9f01-449a-b94c-953a1e205c5b" Name="TaskConditionTaskKinds" IsExternal="true" />
	<SchemeTable ID="f7cd6753-21d7-4095-8c3a-e7175f591ad3" Name="TaskConditionTaskTypes" IsExternal="true" />
</SchemePartition>