import { IViewColumnMetadata, IViewParameterMetadata, RequestParameter, IViewReferenceMetadata, ViewSelectionMode, IViewSubsetMetadata, IViewMetadata, IViewAppearanceMetadata, ViewAppearanceMetadataSealed, ViewColumnMetadataSealed, ViewParameterMetadataSealed, ViewReferenceMetadataSealed, ViewSubsetMetadataSealed, ViewMetadataSealed } from './metadata';
import { SortDirection, SortingColumn } from './sortingColumn';
import { IExtensionMetadata, ExtensionMetadataSealed } from './workplaces/extensionMetadata';
import { Paging } from './paging';
import { MetadataDataSourceTypes } from './metadataDataSourceTypes';
export interface IDataSourceMetadata {
    readonly alias: string;
    readonly appearance: string | null;
    readonly appearances: Array<IViewAppearanceMetadata>;
    readonly caption: string;
    readonly columns: Array<IViewColumnMetadata>;
    readonly defaultSortColumn: string;
    readonly defaultSortDirection: SortDirection | null;
    readonly defaultSortingColumns: Array<SortingColumn>;
    readonly enableAutoWidth: boolean;
    readonly expandingIconName: string;
    readonly exportDataPageLimit: number;
    readonly extensions: Array<IExtensionMetadata>;
    readonly iconName: string;
    readonly id: string;
    readonly multiSelect: boolean;
    readonly pageLimit: number;
    readonly paging: Paging;
    readonly parameters: Array<IViewParameterMetadata>;
    readonly parametersValues: Array<RequestParameter>;
    readonly references: Array<IViewReferenceMetadata>;
    readonly rowCounterVisible: boolean;
    readonly rowCountSubset: string;
    readonly selectionMode: ViewSelectionMode;
    readonly sourceType: MetadataDataSourceTypes;
    readonly subsets: Array<IViewSubsetMetadata>;
    getViewMetadata(): IViewMetadata | null;
    isSpecialSubset(alias: string): boolean;
    seal<T = DataSourceMetadataSealed>(): T;
}
export interface DataSourceMetadataSealed {
    readonly alias: string;
    readonly appearance: string | null;
    readonly appearances: ReadonlyArray<ViewAppearanceMetadataSealed>;
    readonly caption: string;
    readonly columns: ReadonlyArray<ViewColumnMetadataSealed>;
    readonly defaultSortColumn: string;
    readonly defaultSortDirection: SortDirection | null;
    readonly defaultSortingColumns: ReadonlyArray<SortingColumn>;
    readonly enableAutoWidth: boolean;
    readonly expandingIconName: string;
    readonly exportDataPageLimit: number;
    readonly extensions: ReadonlyArray<ExtensionMetadataSealed>;
    readonly iconName: string;
    readonly id: string;
    readonly multiSelect: boolean;
    readonly pageLimit: number;
    readonly paging: Paging;
    readonly parameters: ReadonlyArray<ViewParameterMetadataSealed>;
    readonly parametersValues: ReadonlyArray<RequestParameter>;
    readonly references: ReadonlyArray<ViewReferenceMetadataSealed>;
    readonly rowCounterVisible: boolean;
    readonly rowCountSubset: string;
    readonly selectionMode: ViewSelectionMode;
    readonly sourceType: MetadataDataSourceTypes;
    readonly subsets: ReadonlyArray<ViewSubsetMetadataSealed>;
    getViewMetadata(): ViewMetadataSealed | null;
    isSpecialSubset(alias: string): boolean;
    seal<T = DataSourceMetadataSealed>(): T;
}
