<?xml version="1.0" encoding="utf-8"?>
<SchemePartition SchemeVersion="4.0.0.2" ID="a6d84d24-0461-4c65-aa5d-f41ee300f081" Name="Ocr">
	<Dependencies>
		<SchemePartition ID="29f90c69-c1ef-4cbf-b9d5-7fc91cd68c67" Name="Default" />
	</Dependencies>
	<Description>Library for module of text recognition in files</Description>
	<SchemeTable ID="a5b1b1cf-ad8c-4459-a880-a5ff9f435398" Name="OcrLanguages" IsExternal="true" />
	<SchemeTable ID="e8135496-a897-44b9-bc24-9214646453fe" Name="OcrMappingComplexFields" IsExternal="true" />
	<SchemeTable ID="f60796c1-b504-424d-93c8-2fd5b9107867" Name="OcrMappingFields" IsExternal="true" />
	<SchemeTable ID="46a9cc0e-9492-48ce-8ac8-bc04551a041a" Name="OcrMappingSettingsFields" IsExternal="true" />
	<SchemeTable ID="3a7dbf8d-2f25-4b98-a406-2582bfeee594" Name="OcrMappingSettingsSections" IsExternal="true" />
	<SchemeTable ID="6f34e6c5-93e9-49ed-ad42-63d8a001ded7" Name="OcrMappingSettingsTypes" IsExternal="true" />
	<SchemeTable ID="0c83bfa8-8e9a-454d-b805-6de0c679f4ec" Name="OcrMappingSettingsVirtual" IsExternal="true" />
	<SchemeTable ID="2fb28ad4-1b86-4d22-bc15-2a4943a0bb7f" Name="OcrOperations" IsExternal="true" />
	<SchemeTable ID="ff8635f6-7856-45e1-82cf-6f00315ce790" Name="OcrPatternTypes" IsExternal="true" />
	<SchemeTable ID="b9a84cff-8153-4a81-b9f3-832d59461596" Name="OcrRecognitionModes" IsExternal="true" />
	<SchemeTable ID="d64806e9-ef31-4133-806b-670b178cc5bc" Name="OcrRequests" IsExternal="true" />
	<SchemeTable ID="afee6930-bb0c-48b3-b0ac-3a1447a31d12" Name="OcrRequestsLanguages" IsExternal="true" />
	<SchemeTable ID="aefacd5d-1de1-42ac-86db-ddb98035f498" Name="OcrRequestsStates" IsExternal="true" />
	<SchemeTable ID="f704ecbb-e3b2-4a79-8ca8-222417f3dc4d" Name="OcrResultsVirtual" IsExternal="true" />
	<SchemeTable ID="5455dc3b-79f8-4c06-8cf0-64e63919ab4a" Name="OcrSegmentationModes" IsExternal="true" />
	<SchemeTable ID="4463ae11-e603-4daa-8b93-2e4323abef37" Name="OcrSettings" IsExternal="true" />
	<SchemeTable ID="e432240e-e30a-4568-aa91-bb9a9e55ea61" Name="OcrSettingsPatterns" IsExternal="true" />
</SchemePartition>