import { SubsetKind } from './subsetKind';
import { IViewColumnMetadata, ViewColumnMetadataSealed } from './viewColumnMetadata';
import { ViewSelectionMode } from './viewSelectionMode';
import { IViewSubsetMetadata, ViewSubsetMetadataSealed } from './viewSubsetMetadata';
import { IViewParameterMetadata, ViewParameterMetadataSealed } from './viewParameterMetadata';
import { IViewAppearanceMetadata, ViewAppearanceMetadataSealed } from './viewAppearanceMetadata';
import { IViewReferenceMetadata, ViewReferenceMetadataSealed } from './viewReferenceMetadata';
import { SortingColumn, SortDirection } from '../sortingColumn';
import { Paging } from '../paging';
import { IExtensionMetadata, ExtensionMetadataSealed } from '../workplaces/extensionMetadata';
import { TagsPosition } from 'tessa/ui/tags/tagsPosition';
export interface IViewMetadata {
    alias: string;
    caption: string | null;
    appearance: string;
    appearances: Map<string, IViewAppearanceMetadata>;
    autoWidthRowLimit: number | null;
    columns: Map<string, IViewColumnMetadata>;
    defaultSortColumn: string | null;
    defaultSortDirection: SortDirection | null;
    defaultSortingColumns: SortingColumn[];
    enableAutoWidth: boolean;
    exportDataPageLimit: number;
    extensions: Map<string, IExtensionMetadata>;
    groupingColumn: string | null;
    kind: SubsetKind;
    multiSelect: boolean;
    pageLimit: number;
    paging: Paging;
    parameters: Map<string, IViewParameterMetadata>;
    quickSearchParam: string | null;
    references: Map<string, IViewReferenceMetadata>;
    rowCounterVisible: boolean;
    rowCountSubset: string | null;
    selectionMode: ViewSelectionMode;
    subsets: Map<string, IViewSubsetMetadata>;
    treatAsSingleQuery: boolean;
    treeGroupDisplayValue: string;
    treeGroup: string | null;
    treeGroupId: string;
    treeGroupParentId: string;
    treeHasChildrenColumn: string | null;
    treeId: string;
    treeParentId: string;
    treeRefParam: string | null;
    tagsPosition: TagsPosition;
    seal<T = ViewMetadataSealed>(): T;
}
export interface ViewMetadataSealed {
    readonly alias: string;
    readonly caption: string | null;
    readonly appearance: string;
    readonly appearances: ReadonlyMap<string, ViewAppearanceMetadataSealed>;
    readonly autoWidthRowLimit: number | null;
    readonly columns: ReadonlyMap<string, ViewColumnMetadataSealed>;
    readonly defaultSortColumn: string | null;
    readonly defaultSortDirection: SortDirection | null;
    readonly defaultSortingColumns: ReadonlyArray<SortingColumn>;
    readonly enableAutoWidth: boolean;
    readonly exportDataPageLimit: number;
    readonly extensions: ReadonlyMap<string, ExtensionMetadataSealed>;
    readonly groupingColumn: string | null;
    readonly kind: SubsetKind;
    readonly multiSelect: boolean;
    readonly pageLimit: number;
    readonly paging: Paging;
    readonly parameters: ReadonlyMap<string, ViewParameterMetadataSealed>;
    readonly quickSearchParam: string | null;
    readonly references: ReadonlyMap<string, ViewReferenceMetadataSealed>;
    readonly rowCounterVisible: boolean;
    readonly rowCountSubset: string | null;
    readonly selectionMode: ViewSelectionMode;
    readonly subsets: ReadonlyMap<string, ViewSubsetMetadataSealed>;
    readonly treatAsSingleQuery: boolean;
    readonly treeGroupDisplayValue: string;
    readonly treeGroup: string | null;
    readonly treeGroupId: string;
    readonly treeGroupParentId: string;
    readonly treeHasChildrenColumn: string | null;
    readonly treeId: string;
    readonly treeParentId: string;
    readonly treeRefParam: string | null;
    readonly tagsPosition: TagsPosition;
    seal<T = ViewMetadataSealed>(): T;
}
export declare class ViewMetadata implements IViewMetadata {
    constructor();
    alias: string;
    caption: string | null;
    appearance: string;
    appearances: Map<string, IViewAppearanceMetadata>;
    autoWidthRowLimit: number | null;
    columns: Map<string, IViewColumnMetadata>;
    defaultSortColumn: string | null;
    defaultSortDirection: SortDirection | null;
    defaultSortingColumns: SortingColumn[];
    enableAutoWidth: boolean;
    exportDataPageLimit: number;
    extensions: Map<string, IExtensionMetadata>;
    groupingColumn: string | null;
    kind: SubsetKind;
    multiSelect: boolean;
    pageLimit: number;
    paging: Paging;
    parameters: Map<string, IViewParameterMetadata>;
    quickSearchParam: string | null;
    references: Map<string, IViewReferenceMetadata>;
    rowCounterVisible: boolean;
    rowCountSubset: string | null;
    selectionMode: ViewSelectionMode;
    subsets: Map<string, IViewSubsetMetadata>;
    treatAsSingleQuery: boolean;
    treeGroupDisplayValue: string;
    treeGroup: string | null;
    treeGroupId: string;
    treeGroupParentId: string;
    treeHasChildrenColumn: string | null;
    treeId: string;
    treeParentId: string;
    treeRefParam: string | null;
    tagsPosition: TagsPosition;
    seal<T = ViewMetadataSealed>(): T;
}
