import { CardPermissionFlags } from './cardPermissionFlags';
export declare const CardPermissionFlagValues: {
    Modify: number;
    InsertRow: number;
    DeleteRow: number;
    DeleteCard: number;
    InsertFile: number;
    DeleteFile: number;
    ReplaceFile: number;
    EditNumber: number;
    SignFile: number;
    AllowAllCard: number;
    AllowAllEntry: CardPermissionFlags;
    AllowAllTable: number;
    AllowAllRow: number;
    AllowAllField: CardPermissionFlags;
    AllowAllFile: number;
    ProhibitAllCard: number;
    ProhibitAllEntry: CardPermissionFlags;
    ProhibitAllTable: number;
    ProhibitAllRow: number;
    ProhibitAllField: CardPermissionFlags;
    ProhibitAllFile: number;
    AllCard: number;
    AllEntry: number;
    AllTable: number;
    AllRow: number;
    AllField: number;
    AllFile: number;
};
