import { IKrType } from './krType';
import { KrDocNumberRegistrationAutoAssignmentID } from './krDocNumberRegistrationAutoAssignment';
import { KrDocNumberRegularAutoAssignmentID } from './krDocNumberRegularAutoAssignment';
import { IStorage, StorageObject } from 'tessa/platform/storage';
export declare class KrDocType extends StorageObject implements IKrType {
    constructor(storage: IStorage);
    static readonly idKey: string;
    get id(): guid;
    set id(value: guid);
    static readonly nameKey: string;
    get name(): string;
    set name(value: string);
    static readonly captionKey: string;
    get caption(): string;
    set caption(value: string);
    static readonly cardTypeIdKey: string;
    get cardTypeId(): guid;
    set cardTypeId(value: guid);
    static readonly cardTypeNameKey: string;
    get cardTypeName(): string;
    set cardTypeName(value: string);
    static readonly useApprovingKey: string;
    get useApproving(): boolean;
    set useApproving(value: boolean);
    static readonly useRegistrationKey: string;
    get useRegistration(): boolean;
    set useRegistration(value: boolean);
    static readonly useResolutionsKey: string;
    get useResolutions(): boolean;
    set useResolutions(value: boolean);
    static readonly disableChildResolutionDateCheckKey: string;
    get disableChildResolutionDateCheck(): boolean;
    set disableChildResolutionDateCheck(value: boolean);
    static readonly docNumberRegularAutoAssignmentIdKey: string;
    get docNumberRegularAutoAssignmentId(): KrDocNumberRegularAutoAssignmentID;
    set docNumberRegularAutoAssignmentId(value: KrDocNumberRegularAutoAssignmentID);
    static readonly docNumberRegularSequenceKey: string;
    get docNumberRegularSequence(): string;
    set docNumberRegularSequence(value: string);
    static readonly docNumberRegularFormatKey: string;
    get docNumberRegularFormat(): string;
    set docNumberRegularFormat(value: string);
    static readonly allowManualRegularDocNumberAssignmentKey: string;
    get allowManualRegularDocNumberAssignment(): boolean;
    set allowManualRegularDocNumberAssignment(value: boolean);
    static readonly docNumberRegistrationAutoAssignmentIdKey: string;
    get docNumberRegistrationAutoAssignmentId(): KrDocNumberRegistrationAutoAssignmentID;
    set docNumberRegistrationAutoAssignmentId(value: KrDocNumberRegistrationAutoAssignmentID);
    static readonly docNumberRegistrationSequenceKey: string;
    get docNumberRegistrationSequence(): string;
    set docNumberRegistrationSequence(value: string);
    static readonly docNumberRegistrationFormatKey: string;
    get docNumberRegistrationFormat(): string;
    set docNumberRegistrationFormat(value: string);
    static readonly allowManualRegistrationDocNumberAssignmentKey: string;
    get allowManualRegistrationDocNumberAssignment(): boolean;
    set allowManualRegistrationDocNumberAssignment(value: boolean);
    static readonly releaseRegistrationNumberOnFinalDeletionKey: string;
    get releaseRegistrationNumberOnFinalDeletion(): boolean;
    set releaseRegistrationNumberOnFinalDeletion(value: boolean);
    static readonly releaseRegularNumberOnFinalDeletionKey: string;
    get releaseRegularNumberOnFinalDeletion(): boolean;
    set releaseRegularNumberOnFinalDeletion(value: boolean);
    static readonly hideCreationButtonKey: string;
    get hideCreationButton(): boolean;
    set hideCreationButton(value: boolean);
    static readonly hideRouteTabKey: string;
    get hideRouteTab(): boolean;
    set hideRouteTab(value: boolean);
    static readonly useForumKey: string;
    get useForum(): boolean;
    set useForum(value: boolean);
    static readonly useDefaultDiscussionTabKey: string;
    get useDefaultDiscussionTab(): boolean;
    set useDefaultDiscussionTab(value: boolean);
    static readonly useRoutesInWorkflowEngine: string;
    get useRoutesInWorkflowEngine(): boolean;
    set useRoutesInWorkflowEngine(value: boolean);
}
