import { IAutoCompleteDataSourceContext } from './autoCompleteDataSourceContext';
import { IAutoCompleteItem } from './autoCompleteItem';
import { ICardModel } from '../../interfaces';
import { CardMetadataSectionSealed, CardMetadataColumnSealed } from 'tessa/cards/metadata';
import { ITessaView } from 'tessa/views';
import { CardRow } from 'tessa/cards';
import { ArrayStorage } from 'tessa/platform/storage';
import { CardAutoCompleteSearchMode } from 'tessa/cards/cardAutoCompleteSearchMode';
export declare class AutoCompleteTableDataSourceContext implements IAutoCompleteDataSourceContext {
    constructor(setItemDelegate: (item: IAutoCompleteItem, fields: ReadonlyMap<string, any>) => void, deleteItemDelegate: (item: IAutoCompleteItem) => void, cardModel: ICardModel, referenceSection: CardMetadataSectionSealed, referenceColumn: CardMetadataColumnSealed, refSection: ReadonlyArray<string> | null, view: ITessaView | null, viewParameterAlias: string | null, viewReferencePrefix: string | null, viewMapping: any[] | null, popupColumnsIndexesString: string | null, popupColumnLengthsString: string | null, formatString: string | null, maxResultsCount: number, popupScreenLengthPercent: number, isSaveOrder: boolean, orderColumnId: guid | null, manualInput: boolean, manualInputColumnId: guid | null, searchDelay: number | null, extendendLocalization: boolean, searchMode: CardAutoCompleteSearchMode);
    readonly rows: ArrayStorage<CardRow>;
    readonly referenceColumnNames: ReadonlyArray<string>;
    readonly setItemDelegate: (item: IAutoCompleteItem, fields: ReadonlyMap<string, any>) => void;
    readonly deleteItemDelegate: (item: IAutoCompleteItem) => void;
    readonly cardModel: ICardModel;
    readonly referenceSection: CardMetadataSectionSealed;
    readonly referenceColumn: CardMetadataColumnSealed;
    readonly refSection: ReadonlyArray<string> | null;
    readonly physicalColumns: ReadonlyArray<CardMetadataColumnSealed>;
    readonly view: ITessaView | null;
    get viewAlias(): string | null;
    readonly viewParameterAlias: string | null;
    readonly viewMapping: any[] | null;
    readonly viewReferencePrefix: string | null;
    readonly formatString: string | null;
    readonly maxResultsCount: number;
    readonly complexColumnPref: string;
    readonly complexColumnNames: string[];
    readonly popupScreenLengthPercent: number;
    readonly popupComplexColumnsDisplayIndexes: ReadonlyArray<number> | null;
    readonly popupColumnLengths: ReadonlyArray<number> | null;
    readonly isSaveOrder: boolean;
    readonly orderColumnId: guid | null;
    readonly orderColumnName: string | null;
    readonly manualInput: boolean;
    readonly manualInputColumnId: guid | null;
    readonly manualInputColumnName: string | null;
    readonly searchDelay: number;
    readonly extendendLocalization: boolean;
    readonly searchMode: CardAutoCompleteSearchMode;
}
