<?xml version="1.0" encoding="utf-8"?>
<SchemePartition SchemeVersion="4.0.0.2" ID="f3f630df-d649-43ce-9d5b-75048184a749" Name="Law">
	<Dependencies>
		<SchemePartition ID="29f90c69-c1ef-4cbf-b9d5-7fc91cd68c67" Name="Default" />
	</Dependencies>
	<SchemeTable ID="3dbb9a1f-ae27-4612-aec1-4f077494dfef" Name="LawAdministrators" IsExternal="true" />
	<SchemeTable ID="191308f6-820e-408e-b779-cef96b1b09c0" Name="LawCase" IsExternal="true" />
	<SchemeTable ID="362c9171-6267-42a8-8fd8-7bf39d04533e" Name="LawClients" IsExternal="true" />
	<SchemeTable ID="b4cfec48-deec-40fc-94fc-eae9e645afce" Name="LawPartnerRepresentatives" IsExternal="true" />
	<SchemeTable ID="54244411-fea4-4bdd-b009-fad9c5915882" Name="LawPartners" IsExternal="true" />
	<SchemeTable ID="c0b9d91c-4a9e-4c7a-b7c2-13daa37a1cf9" Name="LawPartnersDialogVirtual" IsExternal="true" />
	<SchemeTable ID="0b3ce213-cc34-469d-a0dd-19a4643b1a49" Name="LawUsers" IsExternal="true" />
	<SchemeTable ID="6c977939-bbfc-456f-a133-f1c2244e3cc3" Name="PersonalRoles" IsExternal="true" />
</SchemePartition>